file:
  upload-path: E:\upload

spring:
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
minio:
  endPoint: http://127.0.0.1:9001
  accessKey: minioadmin
  secretKey: minioadmin